"""Initial migration.

Revision ID: 77cbd7bcb1a9
Revises: 
Create Date: 2024-09-03 15:15:12.003940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cbd7bcb1a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pk_user', sa.String(length=150), nullable=True),
    sa.Column('link_id', sa.String(length=150), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('lynx_url', sa.Text(), nullable=True),
    sa.Column('link_type', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('open_external_url_with_in_app_browser', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('pk_user', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('profile_pic_url_hd', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('following',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('pk_user', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('profile_pic_url_hd', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('id_pk', sa.String(length=150), nullable=True),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('taken_at', sa.String(length=150), nullable=True),
    sa.Column('media_type', sa.BigInteger(), nullable=True),
    sa.Column('image_versions2', sa.String(length=150), nullable=True),
    sa.Column('product_type', sa.String(length=150), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('location_pk', sa.String(length=150), nullable=True),
    sa.Column('user_pk', sa.String(length=150), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('comments_disabled', sa.Boolean(), nullable=True),
    sa.Column('commenting_disabled_for_viewer', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('play_count', sa.BigInteger(), nullable=True),
    sa.Column('has_liked', sa.Boolean(), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('accessibility_caption', sa.Text(), nullable=True),
    sa.Column('usertags', sa.String(length=150), nullable=True),
    sa.Column('sponsor_tags', sa.String(length=150), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_duration', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('resources', sa.String(length=150), nullable=True),
    sa.Column('clips_metadata', sa.String(length=150), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('id_pk', sa.String(length=150), nullable=True),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('taken_at', sa.String(length=150), nullable=True),
    sa.Column('media_type', sa.BigInteger(), nullable=True),
    sa.Column('product_type', sa.String(length=150), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('user_pk', sa.String(length=150), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_duration', sa.BigInteger(), nullable=True),
    sa.Column('sponsor_tags', sa.String(length=150), nullable=True),
    sa.Column('links', sa.String(length=150), nullable=True),
    sa.Column('hashtags', sa.String(length=150), nullable=True),
    sa.Column('locations', sa.String(length=150), nullable=True),
    sa.Column('stickers', sa.String(length=150), nullable=True),
    sa.Column('medias', sa.String(length=150), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('profile_pic_url_hd', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('media_count', sa.BigInteger(), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('following_count', sa.BigInteger(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('account_type', sa.BigInteger(), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=True),
    sa.Column('public_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone_number', sa.String(length=150), nullable=True),
    sa.Column('public_phone_country_code', sa.String(length=150), nullable=True),
    sa.Column('public_phone_number', sa.String(length=150), nullable=True),
    sa.Column('business_contact_method', sa.String(length=150), nullable=True),
    sa.Column('business_category_name', sa.String(length=150), nullable=True),
    sa.Column('category_name', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('address_street', sa.String(length=150), nullable=True),
    sa.Column('city_id', sa.String(length=150), nullable=True),
    sa.Column('city_name', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.BigInteger(), nullable=True),
    sa.Column('longitude', sa.BigInteger(), nullable=True),
    sa.Column('zip', sa.String(length=150), nullable=True),
    sa.Column('instagram_location_id', sa.String(length=150), nullable=True),
    sa.Column('interop_messaging_user_fbid', sa.String(length=150), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('user_pk', sa.String(length=150), nullable=True),
    sa.Column('media_pk', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('profile_pic_url_hd', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('pk', sa.String(length=150), nullable=True),
    sa.Column('user_pk', sa.String(length=150), nullable=True),
    sa.Column('story_pk', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('profile_pic_url_hd', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_mention')
    op.drop_table('post_tag')
    op.drop_table('user')
    op.drop_table('story')
    op.drop_table('post')
    op.drop_table('following')
    op.drop_table('follower')
    op.drop_table('bio_links')
    # ### end Alembic commands ###
