"""empty message

Revision ID: dcd84c55f1ce
Revises: 77cbd7bcb1a9
Create Date: 2024-09-06 20:41:53.796989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd84c55f1ce'
down_revision = '77cbd7bcb1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentions', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('mentions')

    # ### end Alembic commands ###
